import { prisma } from '../database/client';
import { InventoryRepository } from '../database/repositories/inventory.repository';
import { ShipmentRepository } from '../database/repositories/shipment.repository';
import { StubEmbeddingProvider } from '../lib/knowledge/embedding-provider';
import { NoOpPgVectorKnowledgeSearch } from '../lib/knowledge/pgvector-search';
import { InventoryService } from './inventory.service';
import { KnowledgeService } from './knowledge.service';
import { ShipmentService } from './shipment.service';
const shipmentRepository = new ShipmentRepository(prisma);
const inventoryRepository = new InventoryRepository(prisma);
const vectorSearch = new NoOpPgVectorKnowledgeSearch();
const knowledgeEmbedder = new StubEmbeddingProvider();
export const shipmentService = new ShipmentService(shipmentRepository);
export const inventoryService = new InventoryService(inventoryRepository, prisma);
export const knowledgeService = new KnowledgeService(vectorSearch, knowledgeEmbedder);
export { slackEscalationService } from './slack-escalation.service';
export { slackWebhookService } from './slack-webhook.service';
export { workflowOrchestrator } from '../workflows/workflow-orchestrator.service.js';
export { auditService } from './audit.service.js';
export { escalationLogService } from './escalation-log.service.js';
export { conversationService } from './conversation.service.js';
export { conversationHistoryService } from './conversation-history.service.js';
export { messageHistoryService } from './message-history.service.js';
export { escalationHistoryService } from './escalation-history.service.js';
